"""empty message

Revision ID: 1cab3c278790
Revises: 
Create Date: 2020-07-23 01:12:25.037368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cab3c278790'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('man',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('alias', sa.String(length=60), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('age_group', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('hobbies', sa.String(), nullable=True),
    sa.Column('profession', sa.String(), nullable=True),
    sa.Column('personality', sa.String(), nullable=True),
    sa.Column('in_extrovert', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('personal_comment', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    op.create_table('woman',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('alias', sa.String(length=60), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('age_group', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('hobbies', sa.String(), nullable=True),
    sa.Column('profession', sa.String(), nullable=True),
    sa.Column('personality', sa.String(), nullable=True),
    sa.Column('in_extrovert', sa.String(), nullable=True),
    sa.Column('personal_comment', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias'),
    sa.UniqueConstraint('password')
    )
    op.create_table('date',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('man_id', sa.Integer(), nullable=True),
    sa.Column('woman_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['man_id'], ['man.id'], ),
    sa.ForeignKeyConstraint(['woman_id'], ['woman.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('msghertohim',
    sa.Column('msg_id', sa.Integer(), nullable=False),
    sa.Column('woman_sender_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('man_receipeint_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['man_receipeint_id'], ['man.id'], ),
    sa.ForeignKeyConstraint(['woman_sender_id'], ['woman.id'], ),
    sa.PrimaryKeyConstraint('msg_id')
    )
    op.create_table('msghimtoher',
    sa.Column('msg_id', sa.Integer(), nullable=False),
    sa.Column('man_sender_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('woman_receiver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['man_sender_id'], ['man.id'], ),
    sa.ForeignKeyConstraint(['woman_receiver_id'], ['woman.id'], ),
    sa.PrimaryKeyConstraint('msg_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('msghimtoher')
    op.drop_table('msghertohim')
    op.drop_table('date')
    op.drop_table('woman')
    op.drop_table('man')
    # ### end Alembic commands ###
