"""empty message

Revision ID: 7575391878eb
Revises: 
Create Date: 2020-07-19 17:06:03.781686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7575391878eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('todolist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('todo_text', sa.Text(), nullable=True),
    sa.Column('is_todo_complete', sa.Boolean(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('categories', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categories'], ['category.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('todo_text')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todolist')
    op.drop_table('image')
    op.drop_table('category')
    # ### end Alembic commands ###
